# Generated by Django 3.0.7 on 2020-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epidemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('add_num', models.IntegerField(blank=True, null=True)),
                ('count_num', models.IntegerField(blank=True, null=True)),
                ('cure_num', models.IntegerField(blank=True, null=True)),
                ('death_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'epidemic',
                'managed': False,
            },
        ),
    ]
