# Generated by Django 3.0.7 on 2020-06-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicShow', '0003_auto_20200614_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemicinfo',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
