# Generated by Django 3.0.7 on 2020-06-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicShow', '0004_auto_20200614_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidemicinfo',
            name='time',
        ),
    ]
